services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql@14/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=$(POSTGRES_NAME)
      - POSTGRES_DB=$(POSTGRES_DB)
      - POSTGRES_USER=$(POSTGRES_USER)
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)

  backend:
    build: ./backend
    command: uvicorn main:app --reload
    volumes:
      - ./code:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
